<?php

namespace Database\Seeders;

use App\Enums\ElectionFeature;
use App\Models\ElectionPlan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class ElectionPlanSeeder extends Seeder
{
    public function run(): void
    {
        ElectionPlan::create(attributes: [
            'name' => ['en' => 'SILVER', 'hi' => 'रजत'],
            'description' => ['en' => 'A basic plan for small elections.', 'hi' => 'छोटे चुनावों के लिए एक बुनियादी योजना.'],
            'currency' => 'USD',
            'base_fee' => 1499,
            'elector_fee' => 49,
            'features' => [
                ['feature' => ElectionFeature::BallotAccessCommonLink, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAccessUniqueLink, 'is_add_on' => true, 'feature_fee' => 499, 'elector_fee' => 19, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkSms, 'is_add_on' => true, 'feature_fee' => 499, 'elector_fee' => 19, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeEmail, 'is_add_on' => true, 'feature_fee' => 199, 'elector_fee' => 9, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeSms, 'is_add_on' => true, 'feature_fee' => 499, 'elector_fee' => 19, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementSms, 'is_add_on' => true, 'feature_fee' => 0, 'elector_fee' => 9, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyDownload, 'is_add_on' => true, 'feature_fee' => 199, 'elector_fee' => 9, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyEmail, 'is_add_on' => true, 'feature_fee' => 499, 'elector_fee' => 9, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::IpRestriction, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::DeviceRestriction, 'is_add_on' => true, 'feature_fee' => 399, 'elector_fee' => 9, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::EditableVotes, 'is_add_on' => true, 'feature_fee' => 499, 'elector_fee' => 9, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::TrackableVotes, 'is_add_on' => true, 'feature_fee' => 799, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::ElectorEmailUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorPhoneUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorCorrections, 'is_add_on' => true, 'feature_fee' => 499, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateShuffling, 'is_add_on' => true, 'feature_fee' => 99, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSorting, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::CandidatePhoto, 'is_add_on' => true, 'feature_fee' => 199, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSymbol, 'is_add_on' => true, 'feature_fee' => 199, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateTeam, 'is_add_on' => true, 'feature_fee' => 499, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::SegmentedVoting, 'is_add_on' => true, 'feature_fee' => 999, 'elector_fee' => 19, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BoothVoting, 'is_add_on' => true, 'feature_fee' => 999, 'elector_fee' => 19, 'show_in_pricing' => true],
            ],
        ]);

        ElectionPlan::create(attributes: [
            'name' => ['en' => 'GOLD', 'hi' => 'गोल्ड'],
            'description' => ['en' => 'A comprehensive plan for medium-sized elections.', 'hi' => 'मध्यम आकार के चुनावों के लिए एक व्यापक योजना.'],
            'currency' => 'USD',
            'base_fee' => 2499,
            'elector_fee' => 69,
            'features' => [
                ['feature' => ElectionFeature::BallotAccessCommonLink, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAccessUniqueLink, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkSms, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeSms, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementSms, 'is_add_on' => true, 'feature_fee' => 0, 'elector_fee' => 9, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyDownload, 'is_add_on' => true, 'feature_fee' => 199, 'elector_fee' => 9, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::IpRestriction, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::DeviceRestriction, 'is_add_on' => true, 'feature_fee' => 399, 'elector_fee' => 9, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::EditableVotes, 'is_add_on' => true, 'feature_fee' => 499, 'elector_fee' => 9, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::TrackableVotes, 'is_add_on' => true, 'feature_fee' => 799, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::ElectorEmailUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorPhoneUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorCorrections, 'is_add_on' => true, 'feature_fee' => 499, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateShuffling, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSorting, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::CandidatePhoto, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSymbol, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateTeam, 'is_add_on' => true, 'feature_fee' => 499, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::SegmentedVoting, 'is_add_on' => true, 'feature_fee' => 999, 'elector_fee' => 19, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BoothVoting, 'is_add_on' => true, 'feature_fee' => 999, 'elector_fee' => 19, 'show_in_pricing' => true],
            ],
        ]);

        ElectionPlan::create(attributes: [
            'name' => ['en' => 'PLATINUM', 'hi' => 'प्लैटिनम'],
            'description' => ['en' => 'A comprehensive plan for large-sized elections', 'hi' => 'बड़े आकार के चुनावों के लिए एक व्यापक योजना'],
            'currency' => 'USD',
            'base_fee' => 3999,
            'elector_fee' => 99,
            'features' => [
                ['feature' => ElectionFeature::BallotAccessCommonLink, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAccessUniqueLink, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkSms, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeSms, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementSms, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyDownload, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::IpRestriction, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::DeviceRestriction, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::EditableVotes, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::TrackableVotes, 'is_add_on' => true, 'feature_fee' => 799, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorEmailUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorPhoneUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorCorrections, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateShuffling, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSorting, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::CandidatePhoto, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSymbol, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateTeam, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::SegmentedVoting, 'is_add_on' => true, 'feature_fee' => 999, 'elector_fee' => 19, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BoothVoting, 'is_add_on' => true, 'feature_fee' => 999, 'elector_fee' => 19, 'show_in_pricing' => true],
            ],
        ]);

        ElectionPlan::create(attributes: [
            'name' => ['en' => 'SILVER', 'hi' => 'रजत'],
            'description' => ['en' => 'A basic plan for small elections.', 'hi' => 'छोटे चुनावों के लिए एक बुनियादी योजना.'],
            'currency' => 'INR',
            'base_fee' => 150000,
            'elector_fee' => 5000,
            'features' => [
                ['feature' => ElectionFeature::BallotAccessCommonLink, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAccessUniqueLink, 'is_add_on' => true, 'feature_fee' => 5000, 'elector_fee' => 200, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkSms, 'is_add_on' => true, 'feature_fee' => 5000, 'elector_fee' => 200, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeEmail, 'is_add_on' => true, 'feature_fee' => 2000, 'elector_fee' => 100, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeSms, 'is_add_on' => true, 'feature_fee' => 5000, 'elector_fee' => 200, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementSms, 'is_add_on' => true, 'feature_fee' => 0, 'elector_fee' => 100, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyDownload, 'is_add_on' => true, 'feature_fee' => 2000, 'elector_fee' => 100, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyEmail, 'is_add_on' => true, 'feature_fee' => 5000, 'elector_fee' => 100, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::IpRestriction, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::DeviceRestriction, 'is_add_on' => true, 'feature_fee' => 4000, 'elector_fee' => 100, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::EditableVotes, 'is_add_on' => true, 'feature_fee' => 5000, 'elector_fee' => 100, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::TrackableVotes, 'is_add_on' => true, 'feature_fee' => 8000, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::ElectorEmailUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorPhoneUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorCorrections, 'is_add_on' => true, 'feature_fee' => 5000, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateShuffling, 'is_add_on' => true, 'feature_fee' => 1000, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSorting, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::CandidatePhoto, 'is_add_on' => true, 'feature_fee' => 2000, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSymbol, 'is_add_on' => true, 'feature_fee' => 2000, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateTeam, 'is_add_on' => true, 'feature_fee' => 5000, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::SegmentedVoting, 'is_add_on' => true, 'feature_fee' => 10000, 'elector_fee' => 200, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BoothVoting, 'is_add_on' => true, 'feature_fee' => 10000, 'elector_fee' => 200, 'show_in_pricing' => true],
            ],
        ]);

        ElectionPlan::create(attributes: [
            'name' => ['en' => 'GOLD', 'hi' => 'गोल्ड'],
            'description' => ['en' => 'A comprehensive plan for medium-sized elections.', 'hi' => 'मध्यम आकार के चुनावों के लिए एक व्यापक योजना.'],
            'currency' => 'INR',
            'base_fee' => 250000,
            'elector_fee' => 7500,
            'features' => [
                ['feature' => ElectionFeature::BallotAccessCommonLink, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAccessUniqueLink, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkSms, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeSms, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementSms, 'is_add_on' => true, 'feature_fee' => 0, 'elector_fee' => 100, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyDownload, 'is_add_on' => true, 'feature_fee' => 2000, 'elector_fee' => 100, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::IpRestriction, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::DeviceRestriction, 'is_add_on' => true, 'feature_fee' => 4000, 'elector_fee' => 100, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::EditableVotes, 'is_add_on' => true, 'feature_fee' => 5000, 'elector_fee' => 100, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::TrackableVotes, 'is_add_on' => true, 'feature_fee' => 8000, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::ElectorEmailUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorPhoneUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorCorrections, 'is_add_on' => true, 'feature_fee' => 5000, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateShuffling, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSorting, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::CandidatePhoto, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSymbol, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateTeam, 'is_add_on' => true, 'feature_fee' => 5000, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::SegmentedVoting, 'is_add_on' => true, 'feature_fee' => 10000, 'elector_fee' => 200, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BoothVoting, 'is_add_on' => true, 'feature_fee' => 10000, 'elector_fee' => 200, 'show_in_pricing' => true],
            ],
        ]);

        ElectionPlan::create(attributes: [
            'name' => ['en' => 'PLATINUM', 'hi' => 'प्लैटिनम'],
            'description' => ['en' => 'A comprehensive plan for large-sized elections', 'hi' => 'बड़े आकार के चुनावों के लिए एक व्यापक योजना'],
            'currency' => 'INR',
            'base_fee' => 400000,
            'elector_fee' => 10000,
            'features' => [
                ['feature' => ElectionFeature::BallotAccessCommonLink, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAccessUniqueLink, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotLinkSms, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::VerificationCodeSms, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotAcknowledgementSms, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyDownload, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BallotCopyEmail, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::IpRestriction, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::DeviceRestriction, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::EditableVotes, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::TrackableVotes, 'is_add_on' => true, 'feature_fee' => 8000, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorEmailUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorPhoneUnique, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::ElectorCorrections, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateShuffling, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSorting, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => false],
                ['feature' => ElectionFeature::CandidatePhoto, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateSymbol, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::CandidateTeam, 'is_add_on' => false, 'feature_fee' => 0, 'elector_fee' => 0, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::SegmentedVoting, 'is_add_on' => true, 'feature_fee' => 10000, 'elector_fee' => 200, 'show_in_pricing' => true],
                ['feature' => ElectionFeature::BoothVoting, 'is_add_on' => true, 'feature_fee' => 10000, 'elector_fee' => 200, 'show_in_pricing' => true],
            ],
        ]);
    }
}
