<?php

namespace App\Models\Concerns;

use App\Actions\GenerateModelHashKey;

trait HasAutoGeneratedHashKey
{
    protected static function bootHasAutoGeneratedHashKey(): void
    {
        static::saving(function (self $model) {
            $hashKeyName = $model->getHashKeyName();

            if (blank($model->getAttribute($hashKeyName))) {
                $model->setAttribute(
                    $hashKeyName,
                    app(GenerateModelHashKey::class)->execute($model)
                );
            }
        });
    }

    protected function getHashKeyName(): string
    {
        return 'key';
    }
}
