<?php

namespace App\Filament\Election\Pages;

use App\Enums\ElectionPanelState;
use App\Facades\Kudvo;
use App\Filament\Election\Http\Middleware\EnsureStateIsAllowed;
use App\Filament\Election\Pages\Concerns\InteractsWithElection;
use App\Filament\Pages\Concerns\HasStateSection;
use App\Models\Elector;
use Barryvdh\DomPDF\Facade\Pdf;
use Dompdf\Dompdf;
use Filament\Actions\Action;
use Filament\Facades\Filament;
use Filament\Pages\Page;
use Filament\Panel;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Livewire\Attributes\Locked;

class Index extends Page
{
    use HasStateSection;
    use InteractsWithElection;

    protected static string $view = 'filament.election.pages.index';

    protected static ?string $slug = '/';

    public ?ElectionPanelState $state = null;

    #[Locked]
    public ?string $sessionVotes = null;

    public bool $mock;

    public function mount(Request $request): void
    {
        $this->mock = $request->query(key: 'mock', default: false);

        $this->state = Kudvo::getElectionPanelState();

        if ($this->state == ElectionPanelState::Open) {
            $this->redirect(url: Ballot\Index::getUrl(), navigate: $this->isSpa());

            return;
        }

        $this->sessionVotes = Session::pull(key: 'elector_'.($this->getElector()?->getKey()).'_votes');
    }

    public static function getRelativeRouteName(): string
    {
        return 'index';
    }

    public static function getWithoutRouteMiddleware(Panel $panel): string|array
    {
        return [
            EnsureStateIsAllowed::class,
            ...$panel->getAuthMiddleware()
        ];
    }

    public static function canAccess(): bool
    {
        return parent::canAccess(); // TODO: Change the autogenerated stub
    }

    public function getTitle(): string|Htmlable
    {
        return $this->getElection()->name;
    }

    public function isSpa(): bool
    {
        return Filament::getCurrentPanel()->hasSpaMode();
    }

    public function isMock(): bool
    {
        return $this->mock;
    }

    public function getState(): ?ElectionPanelState
    {
        return $this->state;
    }

    public function getStateHeading(): string | Htmlable | null
    {
        return $this->getState()?->getLabel(election: $this->getElection());
    }

    public function getStateIcon(): ?string
    {
        return $this->getState()?->getIcon(election: $this->getElection());
    }

    public function getStateDescription(): string|Htmlable|null
    {
        return $this->getState()?->getDescription(election: $this->getElection(), elector: $this->getElector());
    }

    protected function getStateActions(): array
    {
        return match ($this->getState()) {
            ElectionPanelState::Voted => [
                Action::make(name: 'downloadMyBallot')
                    ->action(action: fn (self $livewire) => response()
                        ->streamDownload(
                            callback: function () use ($livewire) {
                                echo $livewire->generateBallotCopyPdf()
                                    ->output();
                            },
                            name: "ballot-{$livewire->getElection()->code}.pdf",
                        )
                    )
                    ->visible(condition: fn (self $livewire): bool => !Kudvo::isBoothDevice(election: $livewire->getElection()) && filled($livewire->sessionVotes)),
            ],
            default => [],
        };
    }

    protected function getElector(): ?Elector
    {
        /** @var ?Elector $elector */
        $elector = Filament::auth()->user();

        return $elector;
    }

    protected function generateBallotCopyPdf(): Dompdf|\Barryvdh\DomPDF\PDF
    {
        $pdf = Pdf::loadView(
            'pdf.election.ballot-copy',
            [
                'election' => $this->getElection(),
                'elector' => $this->getElector(),
                'votes' => decrypt(value: $this->sessionVotes),
            ],
            [],
            'UTF-8'
        );

        $this->sessionVotes = null;

        return $pdf
            ->setOption([
                'isRemoteEnabled' => true,
            ])
            ->setPaper(size: 'a4');
    }
}
