<?php

namespace App\Models;

use App\Enums\MeetingOnboardingStep;
use App\Enums\MeetingStatus;
use App\Enums\MeetingVotingStatus;
use App\Filament\Imports\ParticipantImporter;
use App\Models\Concerns\HasAutoGeneratedHashKey;
use Filament\Actions\Imports\Models\Import;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Laravel\Cashier\Checkout;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Meeting extends Model
{
    use HasAutoGeneratedHashKey;
    use HasUlids;
    use LogsActivity;

    protected $fillable = [
        'name',
        'description',
        'timezone',
        'voting_starts_at',
        'voting_ends_at',
        'voting_closed_at',
        'published_at',
        'cancelled_at',
        'organisation_id',
        'branch_id',
    ];

    protected $casts = [
        'voting_starts_at' => 'datetime',
        'voting_ends_at' => 'datetime',
        'voting_closed_at' => 'datetime',
        'published_at' => 'datetime',
        'cancelled_at' => 'datetime',
        'organisation_id' => 'int',
        'branch_id' => 'int',
    ];

    protected static function booted(): void
    {
        static::creating(callback: function (self $meeting) {
            if (blank($meeting->code)) {
                $meeting->code = static::generateCode();
            }
        });
    }

    public static function generateCode(): string
    {
        return config(key: 'app.meeting.code.prefix') .
            Str::upper(value: Str::random(length: config(key: 'app.meeting.code.length')));
    }

    public function getRouteKeyName(): string
    {
        return 'code';
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logAll()
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs();
    }

    public function meetingLinkBlasts(): HasMany
    {
        return $this->hasMany(MeetingLinkBlast::class);
    }

    public function scopePublished(Builder $query): Builder
    {
        return $query->whereNotNull(columns: 'published_at');
    }

    public function organisation(): BelongsTo
    {
        return $this->belongsTo(related: Organisation::class);
    }

    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class);
    }

    public function votedParticipants(): HasMany
    {
        return $this->hasMany(related: Participant::class)
            ->scopes(scopes: ['voted']);
    }

    public function nonVotedParticipants(): HasMany
    {
        return $this->hasMany(related: Participant::class)
            ->scopes(scopes: ['nonVoted']);
    }

    public function participantEmails(): HasManyThrough
    {
        return $this->hasManyThrough(
            Email::class,
            Participant::class,
            'meeting_id',
            'notifiable_id',
        )->where('notifiable_type', Participant::class);
    }

    public function participantSmsMessages(): HasManyThrough
    {
        return $this->hasManyThrough(
            SmsMessage::class,
            Participant::class,
            'meeting_id',
            'smsable_id',
        )->where('smsable_type', Participant::class);
    }

    public function participantImports(): BelongsToMany
    {
        return $this->imports()
            ->where('importer', ParticipantImporter::class);
    }

    public function imports(): BelongsToMany
    {
        return $this->belongsToMany(related: Import::class)
            ->using(class: ImportMeeting::class)
            ->withPivot(columns: ['options', 'column_map']);
    }

    /**
     * @return array<int, string>
     */
    public function uniqueIds(): array
    {
        return ['key'];
    }

    public function getOnboardingStep(): ?MeetingOnboardingStep
    {
        if (! $this->participants()->exists()) {
            return MeetingOnboardingStep::AddParticipants;
        }

        if (! $this->resolutions()->exists()) {
            return MeetingOnboardingStep::AddResolutions;
        }

        if ($this->isStatus(MeetingStatus::Onboarding)) {
            return MeetingOnboardingStep::Publish;
        }

        return null;
    }

    public function participants(): HasMany
    {
        return $this->hasMany(related: Participant::class);
    }

    public function resolutions(): HasMany
    {
        return $this->hasMany(related: Resolution::class)
            ->orderBy(column: 'sort');
    }

    /**
     * @param  MeetingStatus|array<int, MeetingStatus>  $status
     */
    public function isStatus(MeetingStatus | array $status): bool
    {
        return in_array($this->status, Arr::wrap($status), true);
    }

    /**
     * @param  MeetingVotingStatus|array<int, MeetingVotingStatus>  $status
     */
    public function isVotingStatus(MeetingVotingStatus | array $status): bool
    {
        return in_array($this->voting_status, Arr::wrap($status), true);
    }

    public function isCheckoutRequired(): bool
    {
        return $this->payments()->doesntExist();
    }

    public function payments(): HasMany
    {
        return $this->hasMany(MeetingPayment::class)
            ->latest();
    }

    public function checkout(User $user): Checkout
    {
        $participantsCount = $this->participants()->count();

        $items = collect(value: [
            [
                'quantity' => 1,
                'price_data' => [
                    'currency' => 'USD',
                    'unit_amount' => 2500,
                    'product_data' => [
                        'name' => 'Base fee',
                    ],
                ],
            ],
            [
                'quantity' => $participantsCount,
                'price_data' => [
                    'currency' => 'USD',
                    'unit_amount' => 100,
                    'product_data' => [
                        'name' => 'Participant fee',
                    ],
                ],
            ],
        ]);

        return $user
            ->allowPromotionCodes()
            ->collectTaxIds()
            ->checkout(
                items: $items->toArray(),
                sessionOptions: [
                    'success_url' => route(name: 'checkout.success') . '?session_id={CHECKOUT_SESSION_ID}',
                    'cancel_url' => route(name: 'checkout.cancel') . '?session_id={CHECKOUT_SESSION_ID}',
                    'automatic_tax' => [
                        'enabled' => true,
                    ],
                    'billing_address_collection' => 'required',
                    'customer_update' => [
                        'address' => 'auto',
                    ],
                    'invoice_creation' => [
                        'enabled' => true,
                        'invoice_data' => [
                            'metadata' => [
                                'related_type' => 'meeting',
                                'related_id' => $this->getKey(),
                            ],
                        ],
                    ],
                    'metadata' => [
                        'related_type' => 'meeting',
                        'related_id' => $this->getKey(),
                    ],
                ],
            );
    }

    protected function getHashKeyName(): string
    {
        return 'short_key';
    }

    protected function votingStartsAtLocal(): Attribute
    {
        return Attribute::make(
            get: fn ($value, array $attributes) => $this->voting_starts_at?->tz(value: $this->timezone),
        );
    }

    protected function votingEndsAtLocal(): Attribute
    {
        return Attribute::make(
            get: fn ($value, array $attributes) => $this->voting_ends_at?->tz(value: $this->timezone),
        );
    }

    protected function isCancelled(): Attribute
    {
        return Attribute::make(
            get: fn ($value, array $attributes) => filled($this->cancelled_at),
        );
    }

    protected function isPublished(): Attribute
    {
        return Attribute::make(
            get: fn ($value, array $attributes) => filled($this->published_at) && ! $this->is_cancelled,
        );
    }

    protected function status(): Attribute
    {
        return Attribute::make(
            get: fn ($value, array $attributes) => match (true) {
                $this->is_cancelled => MeetingStatus::Cancelled,
                $this->is_published => MeetingStatus::Published,
                default => MeetingStatus::Onboarding,
            },
        );
    }

    protected function votingStatus(): Attribute
    {
        return Attribute::make(
            get: fn ($value, array $attributes) => match (true) {
                filled($this->voting_closed_at) => MeetingVotingStatus::Closed,
                $this->voting_ends_at?->isPast() => MeetingVotingStatus::Ended,
                $this->voting_starts_at?->isPast() => MeetingVotingStatus::Open,
                $this->voting_starts_at?->isFuture() => MeetingVotingStatus::Scheduled,
                default => MeetingVotingStatus::NotApplicable,
            },
        );
    }
}
