<?php

namespace App\Models;

use App\Models\Concerns\HasAutoGeneratedHashKey;
use Illuminate\Database\Eloquent\Model;

class ShortLink extends Model
{
    use HasAutoGeneratedHashKey;

    protected $fillable = [
        'destination',
    ];

    protected $casts = [
        'destination' => 'encrypted',
    ];

    public function getRouteKeyName(): string
    {
        return 'key';
    }
}
